version: '3'
services:
  backend:
    build:
      context: SampleJavaApp
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 4

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    ports:
      - "4000:4000"